export enum RejectionCategory {
  POOR_QUALITY_PHOTOS = 'POOR_QUALITY_PHOTOS',
  EXPIRED_DOCUMENTS = 'EXPIRED_DOCUMENTS',
  INFORMATION_MISMATCH = 'INFORMATION_MISMATCH',
  ADDITIONAL_DOCUMENTATION_REQUIRED = 'ADDITIONAL_DOCUMENTATION_REQUIRED',
  OTHER = 'OTHER',
}
