export enum NotificationType {
  // Delivery related
  NEW_DELIVERY_OPPORTUNITY = 'NEW_DELIVERY_OPPORTUNITY',
  NEW_OFFER_RECEIVED = 'NEW_OFFER_RECEIVED',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  OFFER_REJECTED = 'OFFER_REJECTED',
  OFFER_EXPIRED = 'OFFER_EXPIRED',

  // Order related
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_PICKED_UP = 'ORDER_PICKED_UP',
  ORDER_IN_TRANSIT = 'ORDER_IN_TRANSIT',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',

  // Payment related
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  SETTLEMENT_PAID = 'SETTLEMENT_PAID',

  // Incident related
  INCIDENT_CREATED = 'INCIDENT_CREATED',
  INCIDENT_UPDATED = 'INCIDENT_UPDATED',
  INCIDENT_RESOLVED = 'INCIDENT_RESOLVED',

  // General
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  ACCOUNT_UPDATE = 'ACCOUNT_UPDATE',
}
