name: Deploy to Development

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Deploy to Dev
    uses: ./.github/workflows/_deploy-apprunner.yml
    with:
      environment: development
      service_name: mekapal-api-dev
      ecr_repository: mekapal-api-dev
      node_env: development
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      APP_RUNNER_ECR_ROLE_ARN: ${{ secrets.APP_RUNNER_ECR_ROLE_ARN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      AWS_COGNITO_USER_POOL_ID: ${{ secrets.AWS_COGNITO_USER_POOL_ID }}
      AWS_COGNITO_CLIENT_ID: ${{ secrets.AWS_COGNITO_CLIENT_ID }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      APP_AWS_ACCESS_KEY_ID: ${{ secrets.APP_AWS_ACCESS_KEY_ID }}
      APP_AWS_SECRET_ACCESS_KEY: ${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}
